name: Build and deploy Python app to Azure Web App - pacientecare-ia-api (Docker)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push Docker image to ACR
        run: |
          # Variáveis
          ACR_LOGIN_SERVER=${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          IMAGE_NAME=pacientecare-ia-api
          IMAGE_TAG=latest

          # Logar no ACR
          az acr login --name $ACR_LOGIN_SERVER

          # Build da imagem Docker e push para o ACR
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      - name: Deploy Docker image to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pacientecare-ia-api'
          images: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/pacientecare-ia-api:latest
          slot-name: 'Production'

