name: Build and deploy Python app to Azure Web App - pacientecare-ia-api (Docker)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://pacientecareregistry.azurecr.io/
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: pacientecareregistry.azurecr.io/${{ secrets.ACR_USERNAME }}/pacientecare-ia-api:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pacientecare-ia-api'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          images: 'pacientecareregistry.azurecr.io/${{ secrets.ACR_USERNAME }}/pacientecare-ia-api:${{ github.sha }}'
