name: Build and deploy Python app to Azure Web App - pacientecare-ia-api (Docker)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      # Checkout do código
      - uses: actions/checkout@v4

      # Setup do Docker Buildx (para suporte à build multi-plataforma)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login no Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry (ACR)
        uses: docker/login-action@v2
        with:
          registry: pacientecareregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build e Push da imagem Docker para o ACR
      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: pacientecareregistry.azurecr.io/pacientecare-ia-api:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      # Login na Azure (necessário para o deploy na Web App)
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FEA645874D1E4FD58EBB52998BA5AA88 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9AF0A896C35144B6AA1744C27958BE6E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6314B98974B24343B128998E82E40AAB }}

      # Deploy do container para a Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pacientecare-ia-api'
          slot-name: 'Production'
          images: pacientecareregistry.azurecr.io/pacientecare-ia-api:${{ github.sha }}
